version: '3'

services:
  psql:
    container_name: psql
    image: postgres:16-bullseye
    restart: always
    env_file:
      - .env
    command: -p ${DB_PORT}
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  go:
    container_name: go
    image: go
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: sh -c "/root/main"
    expose:
      - ${DB_SERVICE_PORT}
    ports:
      - "${DB_SERVICE_PORT}:${DB_SERVICE_PORT}"
    depends_on:
      - psql

